dist: xenial
language: python
matrix:
  include:
    - python: '3.6'
      env: EXTRA_PACKAGES='dataclasses'
    - python: '3.7'
install:
  - pip install janus $EXTRA_PACKAGES
  - pip install -r requirements-dev.txt
script:
  - pytest tests --cov=aioevents
cache:
  - apt
  - directories:
    - "$HOME/.cache/pip"
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
after_success: codecov
deploy:
  provider: pypi
  user: mpyatishev
  password:
    secure: fYCJPCQv+6+nYOCctUwqfACOIGChsGhfiu38NeFR/zodsZDp70qxk60RV38xcQYWIFPAtxusuipSYenRU57vh3vM6oDb5OJxtxEwuXYyJ0zsecqBVTPAJvmM4ffuTnxK1PCB/kyb5K3+RaeAQJGy8mpOHtK8J8RzcBfdGMP+pHM6jrEPWUVVVBk7+brrt3ACB9G6gN0r16sa4YPbPqVfQKgeT6atGuB3izWjo5Q219FfCskyPLnwnY1alWKiYeWgm9JjZF2T1cMBPKZLxyUe2qzhoDqY8ufI2JxmNLYkTfpaUA3D6vi2npGjtZHs3FSnbQnm77yzIH4SHPVY8Zu3i0qyH2aYfIrpmHtPwjyf3Kr5i4WQBQtHoIPoYCQx6lgVcK6A6egmgJieRC2IS2lattol0Vx8LBAFF2hX5P+ts2RcdCVLtalaAkrMSY7LEW0cnkniBq4AnlbKzKX2q5UK+PSeVYPhVBxD4rVrMuIqSaCjvZI/ZbAjqCvzP2+QfB9TrcPznYtvoWLq63UZYWFu1jqjMp1fC432D/4AA3HYW0uR3bpvGzh2N+epz9EhCD76X4qEFuhlxZMYvtmXl8WzVQ3fEhM3/Tsn/PlIwQn76P5fa4lYR+LP0D2YyQmUBplu9MfE+uaeTGMxd60uBCiPJGfNsziJk4qW+NyFElITsFE=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    # tags: true
    all_branches: true
    python: 3.7
