dist: xenial
language: python
matrix:
  include:
    - python: '3.6'
      env: EXTRA_PACKAGES='dataclasses'
    - python: '3.7'
install:
  - pip install janus $EXTRA_PACKAGES
  - pip install -r requirements-dev.txt
script:
  - pytest tests --cov=aioevents
cache:
  - apt
  - directories:
    - "$HOME/.cache/pip"
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
after_success: codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  on:
    tags: true
    all_branches: true
    python: 3.7
  user: mpyatishev
  passwd:
    secure: FBIwxAx3gM6kN5hi0G5NIv0Qqnc8/LTPK1TKcx8TLmoqMwK59cn0gTwrCGaQjjyJEBygBAkS8ZlGYrw5XzA3Zl5WUooD19vhpSsTT8p/L9tnjvT3ZF5XbuCn6Ult5FH4Twwjd2nlvPMruBcH6ZSwuQBgGGOnHkDwDccMHraIqpmYIJXndpO3rgcYg3M4sWItmTvmh9pLjsgy1e+2SqW3b2yZRpsimfXUjZ3j37q/IVUjcAlBHNmjbScQqgnmdQkbGXs+zXEvoced8vqy9oXIDTfIdicgVQVaF33xWmTl7FiXJC0zHmwlTTmnGISn0Mh8W70QwfhXAFJm39ob9tWznoQJ8CvAb3jnC7+Y1W7qGfYfYBH89GNQTKaZcZFY5mXWu4cb95n1AUq6uv9+2TkXQVf963ITQdeW+ZIdtcx9MkbR1IwhmeiTP6P7sFWQav+e1NT7nChkcBL67vaLCHiZ3RrYNObKwIASbSGw+8BYrajt12taOa1gZm+jB+ESGhuwUpYcRzlk0js0NBoL1rxtftXGn5UcTmPfdCSrF/6eAfBn6wIiXHhbLWv/LGpcn00/iMBWObxLYmeCBkpDMuVNqkspi+/jtkB0XOVP5iXS/VLeOvJYHpd92ikPdS+nnj50UZJJL6kJfUvpRwHT8QbRHo7ryV+KQvme0HqLR1+3/lk=
