language: python

python:
  - "3.6"
  - "3.7"


install:
  - pip install -r requirements-dev.txt

script:
  - python setup.py check -rms
  - pytest tests --cov=aioevents
  - mypy aioevents


cache:
  - apt
  - directories:
    - $HOME/.cache/pip


before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

after_success:
    codecov

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    all_branches: true
    python: 3.6
