dist: xenial   # required for Python >= 3.7
language: python

matrix:
  include:
    - python: '3.6'
      env: EXTRA_PACKAGES='dataclasses'
    - python: '3.7'

install:
  - pip install janus $EXTRA_PACKAGES
  - pip install -r requirements-dev.txt

script:
# - python setup.py check -rms
  - pytest tests --cov=aioevents
  - mypy aioevents


cache:
  - apt
  - directories:
    - $HOME/.cache/pip


before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

after_success:
    codecov

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    all_branches: true
    python: 3.7
