dist: xenial
language: python
matrix:
  include:
    - python: '3.6'
      env: EXTRA_PACKAGES='dataclasses'
    - python: '3.7'
install:
  - pip install janus $EXTRA_PACKAGES
  - pip install -r requirements-dev.txt
script:
  - pytest tests --cov=aioevents
cache:
  - apt
  - directories:
    - "$HOME/.cache/pip"
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
after_success: codecov
deploy:
  provider: pypi
  user: mpyatishev
  password:
    secure: SpSvNoXYs665tSlvv07xPlZ1Vo6EHG/6PC9wPTpHLkt4AvQqOsYJfkdljxY2YXm/eHmhHUg+V5WIDsIRqjMWUF8UxbUV3WwRs+wE6NJ6CrknHAwEAISA20makidUR49huZTql6j3QgumRRJPp7bDGKPods0PF2usvSL8Hc2lbhUGlSINBkV7RW3fAToLEzVIyl+3OgjumScicmg9xY55IzB4FmnR3OIWEZnEnatAcqupeA6Hg3dq4nUPRyJFC7b2uLNi0uJCfn5hwLUC4fSa/UqZJeXX9AuYzyCdSJOavPMtWV60vGuTLNnAFZA4LsS/9mSez2n6hh69Djzrb+WRZ+C9OUORidRkEvsiK7Kz50QsP48KiZFgGy0eZKPum9OD6/9eQMd6YbdWFFGC68HBgwpZCcpAKYU27lB7wmd5hAM85s4e0uP+K/WNHA7l09LRFJa3nWuuIRO+dH58+U1QgnrLUDZdHlopHORX/bytPJrOM9dnF+Mn/3sceWaAc6H5JmvStqh3dO77BsYCO8gOuzbyagdUzdc3aAQkJ1XPEF5ezEvjthVbCwX53vSslIWKZ/DX55TSF4h8KP6mCKlcdnBq1rHhNMJtHvzM7LTG4dLS1bNxOHD9froiBfW4WUU6opwObukMlGB7rgAkniBgKpQ4MPKIdy7aCjeqiLGyAcs=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    # tags: true
    all_branches: true
    python: 3.7
